# Generated by Django 5.0.6 on 2024-05-26 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='domain',
            new_name='backend_domain',
        ),
        migrations.AddField(
            model_name='organization',
            name='frontend_domain',
            field=models.CharField(default='http://localhost:5137', max_length=255),
            preserve_default=False,
        ),
    ]
